# Generated by Django 4.1.5 on 2023-02-10 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='dataFotografia',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
